# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
- development

pool:
  vmImage: 'windows-2019'

steps:
- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
    verboseOutput: true
- task: VulnerabilityAssessment@0
- task: PoliCheck@1
  inputs:
    inputType: 'Basic'
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'
    result: 'PoliCheck.xml'
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    useDefaultDetectors: false
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: PublishSecurityAnalysisLogs@2
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'